export const TableHeader = [
  { label: 'Name', value: 'offerName', checked: true, sortable: true },
  {
    label: 'Description',
    value: 'offerDescription',
    checked: true,
    sortable: true
  },
  {
    label: 'Start Date',
    value: 'offerStartDate',
    checked: true,
    sortable: true
  },
  { label: 'End Date', value: 'offerEndDate', checked: true, sortable: true },
  {
    label: 'Status',
    value: 'enabledIndicator',
    checked: true,
    sortable: false
  },
  { label: 'Last Update', value: 'modifiedDate', checked: true, sortable: true }
];

export const TableData = [
  {
    communityCode: 'GAPCL',
    offerId: 105,
    offerName: 'Burger King 2 for 1 burgers',
    offerType: 'VOP offer type',
    offerDescription: 'Buy any hamburger and get the same burger for free.',
    offerStartDate: '2023-04-01 00:00:00:000',
    offerEndDate: '2023-11-30 23:59:59:000',
    enabledIndicator: false,
    metadata: 'METADATA: List of name-value pair',
    extendedOfferId: null,
    offerTitle: 'Burger King 2 for 1 burgers',
    offerTerms: null,
    offerFixedDesc: null,
    offerExtraTerms: null,
    offerTempName: null,
    offerAwardFixed: null,
    offerAwardPercent: null,
    offerAwardMax: null,
    offerMinSpend: null,
    merchantName: null,
    offerUrl: null,
    merchantImageUrlSmall: null,
    merchantImageUrlMedium: null,
    merchantImageUrlLarge: null,
    offerSource: null,
    offerLanguageCode: null,
    offerRegion: null,
    cardLinked: false,
    createdDate: '2023-03-28 01:38:01:873',
    modifiedDate: '2023-03-28 01:38:01:873'
  },
  {
    communityCode: 'GAPCL',
    offerId: 101,
    offerName: 'Starbucks Frappe Special',
    offerType: 'VOP offer type',
    offerDescription: 'Discount $1 from any Frappe, medium or larger',
    offerStartDate: '2023-03-25 00:00:00:000',
    offerEndDate: '2023-12-31 23:59:59:000',
    enabledIndicator: true,
    metadata: 'METADATA: List of name-value pair',
    extendedOfferId: null,
    offerTitle: 'Starbucks Frappe Special',
    offerTerms: null,
    offerFixedDesc: null,
    offerExtraTerms: null,
    offerTempName: null,
    offerAwardFixed: null,
    offerAwardPercent: null,
    offerAwardMax: null,
    offerMinSpend: null,
    merchantName: null,
    offerUrl: null,
    merchantImageUrlSmall: null,
    merchantImageUrlMedium: null,
    merchantImageUrlLarge: null,
    offerSource: null,
    offerLanguageCode: null,
    offerRegion: null,
    cardLinked: false,
    createdDate: '2023-03-28 01:38:01:853',
    modifiedDate: '2023-03-28 01:38:01:853'
  },
  {
    communityCode: 'GAPCL',
    offerId: 103,
    offerName: 'Walmart VIP Sale',
    offerType: 'VOP offer type',
    offerDescription: 'VIP customers save 10% on all non-grocery products',
    offerStartDate: '2023-03-27 00:00:00:000',
    offerEndDate: '2023-12-29 23:59:59:000',
    enabledIndicator: true,
    metadata: 'METADATA: List of name-value pair',
    extendedOfferId: null,
    offerTitle: 'Walmart VIP Sale',
    offerTerms: null,
    offerFixedDesc: null,
    offerExtraTerms: null,
    offerTempName: null,
    offerAwardFixed: null,
    offerAwardPercent: null,
    offerAwardMax: null,
    offerMinSpend: null,
    merchantName: null,
    offerUrl: null,
    merchantImageUrlSmall: null,
    merchantImageUrlMedium: null,
    merchantImageUrlLarge: null,
    offerSource: null,
    offerLanguageCode: null,
    offerRegion: null,
    cardLinked: false,
    createdDate: '2023-03-28 01:38:01:867',
    modifiedDate: '2023-03-28 01:38:01:867'
  }
];
